export { AdminCreateNoticePage } from './AdminCreateNotice';
export { AdminDeletedPage } from './AdminDelete';
export { AdminNoticePage } from './AdminNotice';
export { AdminNoticeDetailPage } from './AdminNoticeDetailPage';
export { AdminPermitPage } from './AdminPermit';
export { AdminPostReportPage } from './AdminPostReport';
export { AdminReviewReportPage } from './AdminReviewReport';
export { AdminUpdateNoticePage } from './AdminUpdateNotice';
export { AdminUserPage } from './AdminUser';
